#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for access/zedstore
#
# IDENTIFICATION
#    src/backend/access/zedstore/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/access/zedstore
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = zedstoream.o zedstore_btree.o zedstore_compression.o zedstoream_handler.o zedstore_meta.o

include $(top_srcdir)/src/backend/common.mk
